### PR TITLE
Test of the hypothesis that the selected number of factors is sufficient

### PR DESCRIPTION
**Pull request by aglebov**
This follows the implementation in `factanal` in R.

Example output from R:
```
Call:
factanal(x = stocks_returns, factors = 2, rotation = "none")

Uniquenesses:
  GM_AC    F_AC  UTX_AC  CAT_AC  MRK_AC  PFE_AC  IBM_AC MSFT_AC 
  0.399   0.423   0.718   0.714   0.519   0.410   0.760   0.749 

Loadings:
        Factor1 Factor2
GM_AC    0.693  -0.348 
F_AC     0.692  -0.313 
UTX_AC   0.531         
CAT_AC   0.529         
MRK_AC   0.551   0.421 
PFE_AC   0.574   0.511 
IBM_AC   0.490         
MSFT_AC  0.499         

               Factor1 Factor2
SS loadings      2.643   0.666
Proportion Var   0.330   0.083
Cumulative Var   0.330   0.414

Test of the hypothesis that 2 factors are sufficient.
The chi square statistic is 564.66 on 13 degrees of freedom.
The p-value is 2.6e-112
```

The corresponding output in Python:
```
>> fa.sufficiency_test(returns.shape[0])
(564.6559390887768, 13, 2.599924619787569e-112)
```

### CODE REVIEW

**Comment by desilinguist** [comment]
Thanks so much for contributing, @aglebov! Would you be okay with submitting a PR to this repo directly so we can make sure that PR checks are run too? I can add you as a collaborator.

**Comment by aglebov** [comment]
> Thanks so much for contributing, @aglebov! Would you be okay with submitting a PR to this repo directly so we can make sure that PR checks are run too? I can add you as a collaborator.

Thanks for getting back to me quickly! I was going to add a few tests for this new functionality before submitting the pull request for review, but happy to follow your guidance in any case.

**Comment by desilinguist** [comment]
Tests would be great! I added you to the repo as a collaborator so you can move the PR here and work on it. Thanks again!

**Comment by aglebov** [comment]
> Tests would be great! I added you to the repo as a collaborator so you can move the PR here and work on it. Thanks again!

I've added a test for the new function plus an R script to generate the baseline output for the test. Please let me know if there are any concerns or suggestions.

**Comment by desilinguist** [comment]
@aglebov I would like to make some stylistic changes to the code. Would you be okay if I pushed commits to your branch or would you prefer merging this as is and then making my changes in a separate PR?

**Comment by desilinguist** [comment]
I can confirm that the tests pass locally for me too and that the code coverage is the same. I will push my minor changes and merge this PR. Thank you so much for the contribution @aglebov!

**Review by desilinguist — APPROVED** [review]

**Pull request merged**
