### PR TITLE
added inverse_transform method

### PR DESCRIPTION
**Pull request by Jehaumont**
Added inverse_transform to transform the factor scores back to the original data space. This method is similar to the inverse_transform in PCA of scikit learn library. This method is thus useful when you want to compare PCA and FA.

### CODE REVIEW

**Comment by jbiggsets** [comment]
Thanks very much for doing this! I may make a few minor formatting changes, but I'll merge this soon.

**Comment by desilinguist** [comment]
@jbiggsets oh and this one is outstanding too.

**Comment by desilinguist** [comment]
Sorry for the delay on this @Jehaumont ! Do you think you will have time to add a test for this change? If so, that'd be very much appreciated.

**Comment by Jehaumont** [comment]
Hi @desilinguist, sorry for my delay as well. I now really busy with some image processing and thus currently not using factor analysis. I'm also not very familiar with writing tests, so it would take me too much to do so at this moment.

**Comment by jbiggsets** [comment]
Hi @Jehaumont, I'm going to close out this PR for now, since I actually can't get it working.  

I tested it locally, and it seems like there are a few bugs in the code. (For example, on line 787, I'm not sure where `X.loads.T` comes from.) More than that, I'm actually not sure this works out mathematically the same way for factor analysis that it does for PCA. In general, I don't think an inverse transformation is very easy with factor analysis, which is why `sklearn` has only implemented it for `PCA()` and not `FactorAnalysis()`. (See [here](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FactorAnalysis.html) and [here](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html).)

If I'm missing something and you're able to fix some of these bugs at some point and add some unit test to demonstrate that this is working properly, please feel free to re-submit the PR. Sorry this took so long to review.

**Pull request closed without merging**
