### PR TITLE
Migrate circle 2.0 and allow users to pass correlation matrix directly

### PR DESCRIPTION
**Pull request by jbiggsets**
This pull request does two things.

1. Update `factor_analyzer.py` to allow users to pass a correlation matrix to various methods, rather than passing the full data set. This is particularly imporant for cases where users do not want to rely on the Pearson correlation, but instead want to use polychoric correlation, for example, with binary data. To indicate that the correlation matrix is being used, users can now pass a `use_corr_matrix=True` argument to the `analyze()` method and other associated methods. Two new tests have been added to make sure this works. This addresses Issue #15.

2. Migrate to Circle CI 2.0. As part of this update, we are also migrating to Circle CI 2.0. This involved adding a new `.circleci/config.yml` file and removing the old `circle.yml` file. There seem to be some issues with coverage being reported as part of the PR, so we will have to either (1) check coverage locally, or (2) go to the Coveralls site directly. (Coveralls and Circle CI have not been particularly responsive to people having trouble with webhooks. See [here](https://github.com/lemurheavy/coveralls-public/issues/1151)  and [here](https://discuss.circleci.com/t/coveralls-with-circleci-2-0/24051).)

### CODE REVIEW

**Comment by desilinguist** [comment]
So, does this mean that we won't ever see coverage reported if we continue to use CircleCI?

**Comment by jbiggsets** [comment]
> So, does this mean that we won't ever see coverage reported if we continue to use CircleCI?

**Comment by jbiggsets** [comment]
Yeah, unfortunately. Other suggestions? 

I spent a while trying to figure this out with CircleCI and couldn't get it working. The other option we discussed was switching to Travis (or some other CI platform). I looked into that briefly, but ultimately didn't spend a lot of time on it.

Thoughts?

**Review by desilinguist — APPROVED** [review]
LGTM :+1:

**Pull request merged**
